### PR TITLE
Publish curation information

### PR DESCRIPTION
**Pull request by olaaustine**

### CODE REVIEW

**Review by dglemos — COMMENTED** [review]
Variant types to be fixed:
- `stop_loss` -> `stop_lost`
- `5_prime_UTR_variant` and `3_prime_UTR_variant` are being converted to `five_prime_UTR_variant` and `three_prime_UTR_variant`. The correct terms are `5_prime_UTR_variant` and `3_prime_UTR_variant`.

**Review by dglemos — COMMENTED** [review]
The only mandatory field to create a curation record is the locus.
I created a record with only locus, however when I click to update the record I get the following error message:
`publications is undefined`

**Review by dglemos — COMMENTED** [review]
Screenshot 2024-08-07 at 11 38 00
When I create a new curation record I get these two message boxes.
It should only return the success box.
The same happens when I update a record.

**Comment by dglemos** [comment]
Screenshot 2024-08-07 at 11 42 15
The button `Update and Publish` could be renamed to `Save & Publish` or just `Publish`.

**Comment by dglemos** [comment]
Screenshot 2024-08-07 at 11 47 53
This message shouldn't include the check mark icon, technically it is an error message. I would remove the check mark and the "Info" and only display the message "Unable to publish data.The following mandatory fields are missing: disease, confidence, publication, panel, allelic_requirement, molecular_mechanism". (There is a missing space before The)

**Comment by dglemos** [comment]
Check the disease name for "<gene>-related".

**Comment by dglemos** [comment]
There is something wrong with the info/error messages.

In this example I tried to publish a record but it failed:
Screenshot 2024-08-07 at 14 23 33

Next, I updated the data and saved it which was done successfully. However, the page includes the previous error message + new success message:
Screenshot 2024-08-07 at 14 23 48

**Comment by dglemos** [comment]
When a record is published, while the code is still running the page shows an error message for a few seconds. When the API finally publish it the message changes to success (as it should). 
The success message should be on another page (it should behave as "Save draft" button).

**Comment by olaaustine** [comment]
> Collaborator

This has been fixed in my latest push( just responding to keep track)

**Comment by dglemos** [comment]
If we try to publish an entry with missing mandatory data we get the following message box
Screenshot 2024-08-14 at 18 32 19

This box should only have the message: 
`Unable to publish data.The following mandatory fields are missing: ...`
The check mark on top doesn't make sense since this is an error message. 
The "Update current record" and "Add another G2P record" buttons don't seem relevant here - you can remove them. Actually "Add another G2P record" is not pointing to the correct page and "Update current record" doesn't do anything.

**Review by dglemos — APPROVED** [review]
The new page is working.
We can make small corrections later.

**Pull request merged**
